import { profile_props } from "./data_types";

const props_empty: profile_props = {
  collections: [
    {
      id: 0,
      address: "",
      name: "",
      description: "",
      image_url: "",
      external_url: "",
      market_cap: 0,
      nfts: [
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
      ],
    },
    {
      id: 0,
      address: "",
      name: "",
      description: "",
      image_url: "",
      external_url: "",
      market_cap: 0,
      nfts: [
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
      ],
    },
    {
      id: 0,
      address: "",
      name: "",
      description: "",
      image_url: "",
      external_url: "",
      market_cap: 0,
      nfts: [
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
      ],
    },
    {
      id: 0,
      address: "",
      name: "",
      description: "",
      image_url: "",
      external_url: "",
      market_cap: 0,
      nfts: [
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
        {
          name: "",
          image_url: "",
          description: "",
          collection: "",
          collection_size: null,
          collection_address: "",
          token_id: "",
          external_url: "",
          last_sale_price: 0,
          last_sale_symbol: "ETH",
          rarity_rank: null,
          properties: null,
        },
      ],
    },
  ],
  user: {
    username: "-",
    description: "-",
    networth: 0,
    address: "",
    collections_filter: [],
    collections_list: [],
    profile_image_url: "./icons/icon-192x192.png",
  },
};

export default function get_empty_profile_props(): profile_props {
  return props_empty;
}
